# Basic neural network without hidden layers

Create a Simple Neural Network in Python from Scratch - https://www.youtube.com/watch?v=kft1AJ9WVDk

- Problem set

|           | i1 | i2 | i3 | Output |
|-----------|----|----|----|--------|
| Example 1 | 0  | 0  | 1  | 0      |
| Example 2 | 1  | 1  | 1  | 1      |
| Example 3 | 1  | 0  | 1  | 1      |
| Example 4 | 0  | 1  | 1  | 0      |

New situation: [1, 0, 0] -> ?

In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

training_inputs = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
])

training_outputs = np.array([[0, 1, 1, 0]]).T

# Initialize random weights
np.random.seed(1)
# 3x1 matrix with values from -1 to 1 and mean 0
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print('Random starting synaptic weights: ')
print(synaptic_weights)

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


Training process
1. Take the inputs from the training example, and put them through
our formula to het the neuron's output.
2. Calculate the error which is the difference between the output we got
and the actual output.
3. Depending on the severeness of the error, adjust the weights.
4. Repeat the process 20,000 times.

In [3]:
for iteration in range(20000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - outputs
    adjustments = error * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
print('Synaptic weights after training: ')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs)

Synaptic weights after training: 
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Outputs after training: 
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]


Now we have a trained neural network. We can use it to predict the output

In [4]:
# Predict new data
new_inputs = np.array([1, 0, 0])
output = sigmoid(np.dot(new_inputs, synaptic_weights))
print('Output data: ', output)

Output data:  [0.99996897]


In [5]:
new_inputs1 = np.array([0, 0, 0])
output1 = sigmoid(np.dot(new_inputs1, synaptic_weights))
print('Output data: ', output1)

Output data:  [0.5]


In [6]:
new_inputs2 = np.array([0, 1, 0])
output2 = sigmoid(np.dot(new_inputs2, synaptic_weights))
print('Output data: ', output2)

Output data:  [0.44857949]
